### ISSUE TITLE
103 - Úprava oznámení projektů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#55]
1) Upravit odesílání emailů podle změn navržených zde: https://docs.google.com/document/d/16ByqpA4RaB96F5YwT5no9313LRJknlbo7lwGo0YqZcM/edit

2) Posunout generování potvrzení až na fázi, kdy je kliknuto na "Zapsat" (posun do P1) v AMČR, tj. negenerovat potvrzení hned po oznámení pomocí formuláře, ale až po jeho kontorle a schválení.

3) V oznamovacím formuláři upravit texty podle: [1_2_texty_zahlavi.docx](https://github.com/ARUP-CAS/aiscr-amcr/files/3281244/1_2_texty_zahlavi.docx)

4) Upravit popisek pole "Katastr" na "Katastrální území"

**Comment by pbartosova** [comment]
Základní odhad 3MD.

**Comment by Najiva** [comment]
popisek pole "Katastr" existuje jak v klientské aplikaci tak v oznamovacím formuláři (server). Je potřeba ho změnit na obou místech, nebo jen v aplikaci, nebo jen ve formuláři?

**Comment by motyc** [comment]
Stačí jej změnit v na webu. Jde jen o srozumitelnost kvůli externím uživatelům...

**Comment by Najiva** [comment]
Issue je predbezne hotove, je potreba to jeste otestovat. Vsechno je na branchi #55. Zmeny byly pouze na servru.

**Comment by motyc** [comment]
Prosím ještě o drobnou opomenutou úpravu - označený email v potvrzení ve verzi pro Moravu upravit na "oznameni@arub.cz". Děkuji

![image](https://user-images.githubusercontent.com/20186892/63420033-2e786200-c406-11e9-978a-2293d9fb4b34.png)

**Comment by Najiva** [comment]
Ano kouknu nato.

**Comment by pbartosova** [comment]
Nasazeno na test i s novym pozadavkem.

**Comment by motyc** [comment]
1) Nemohu testovat, protože soubory v sink mají nulovou velikost a jsou prázdné.
2) OK
3) OK
4) OK
5) OK

**Comment by pbartosova** [comment]
viz 1. To je zajimave, zacalo se to dit az vcera.

**Comment by motyc** [comment]
Místo už je tuším opraveno, ale maily stále nechodí. Prosím o opravu, ať to můžeme otestovat a nasadit.

**Comment by Najiva** [comment]
Bylo potreba jeste zapnout smtp-sink. Uz by to melo fungovat.

**Comment by motyc** [comment]
Otestováno. Jsou třeba dvě drobné korektury v mailech, jinak potvrzuji.

**Comment by Najiva** [comment]
Korektury na testu.

**Comment by motyc** [comment]
Potvrzuji
