### ISSUE TITLE
Vyčištění staré proj. dokumentace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#57]
Není dokončeno. Poslední komunikace s @vbar z 1. 2. 2019 zněla:

> Tak jsem zkusil spustit tu jednorázovou akci (force_clean_old), a ona mi spadla...:-( Navíc nemůžu v logu najít relevantní řádky (aplikace má napilno a log se prudce zvětšuje), takže myslím že bezpečnější bude počkat na nějaký čas menší aktivity a čistit až příští týden...

Nutno dořešit co nejdříve.

**Comment by pbartosova** [comment]
Převzatý skript byl přepsán do Pythonu a bylo doplněno logování, které umožnilo odhalit a vyřešit problémy, které se objevovaly pouze na produkci. Skript je v gitu amcr_serveru v adresáři extras ve zvláštní branch.
Skript je nutno spouštět jako uživatel www-data. NIKDY jako root! Pokud se skript spustí jako root, spustí se jako root i LibreOffice, které si vytvoří adresář /var/spool/libreoffice/uno_packages/cache/uno_packages, ke kterým má pak přístup pouze root. To způsobí, že nelze vytvářet a ukládat žádná nova oznámení apod. Vytvořený adresář je nutné smazat, rm -rf /var/spool/libreoffice/uno_packages/cache/uno_packages.
Chyba je reportována zde https://bugs.documentfoundation.org/show_bug.cgi?id=123861.
