### ISSUE TITLE
Nejde exportovat CSV "Nález"

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#59]
Vrací error 500 na produkci i testu.

Prosím řešit brzy (nefunguje teď ani pro indexaci Digiarchivem).

Bylo by dobré implementovat nějaký test, který by upozornil, že exporty přestaly v nějakém bodě fungovat. Už se to párkrát stalo a přichází se na to nyní celkem náhodně a s velkým odstupem.

**Comment by pbartosova** [comment]
Export dříve fungoval? Nebo jste ho jen nezkoušeli a proto se na to nepřišlo dříve?

**Comment by motyc** [comment]
Ono je otázka, co je dříve... Vím jistě, že to fungovalo správně cca v březnu. Poté už jsem to netestoval.

**Comment by pbartosova** [comment]
Opraveno na testu.

**Comment by motyc** [comment]
Potvrzuji.
