### ISSUE TITLE
159 - Ident_cely v bibliografii

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#6]
Při potvrzení bibliografie se neaktualizuje pole ident_cely. Liší se tak skutečný identifikátor BIB od toho, který je zapsaný v poli ident_cely, a který se zároveň objevuje na exportu tabulek externi_zdroj a externi_odkaz. Tyto případy jde poznat podle toho, že se liší obsah pole "poradi" od číselné hodnoty v BIB-xxxx. V samotné aplikaci to nejde poznat, protože tam se to zjevně generuje dynamicky z více polí.

**Comment by Najiva** [comment]
REPRODUKCE: Jako uzivatel admin po pridani nove bibliografie chci aby pri potvrzeni teto nove bibliografie se docasny nazev, ktery je ve sloupci ident_cely tabulky externi_zdroj prepsal vygenerovanym nazvem zalozenem na poradi bibliografie (sloupec poradi). Napr. pri poradi 8 na BIB-0000008. Je to tak?

**Comment by motyc** [comment]
Ano, to by mělo být ono. Pokud se tedy podle správného klíče nastavuje hodnota pole `poradi` u potvrzených záznamů. Podle záznamu `id` 778463 se ale zdá, že ano.

**Comment by Najiva** [comment]
Fix uz je v repozitari branch row159 ale neni na testu, vzhledem k tomu ze je tento bux v milestonu 5.9.9. Bude pak na produkci potreba opravit hodnotu pole ident_cely pro stavajici zaznamy v tabulce externi_zdroj.

**Comment by pbartosova** [comment]
Nasazeno na testu.
