### ISSUE TITLE
Úvodní stránka AMČR

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/aiscr-amcr#60]
Vytvoření hlavní stránky pro web AMČR.

**Comment by pbartosova** [comment]
1. První pohled do AMČR
a) Hlavní stránka bude zobrazovat pohled pro anonyma
nebo
b) Hlavní stránka bude obsahovat obecné informace a bude nutné se přihlásit. Analogie stávajícího přístupu do AMČR, kdy je nutné potvrdit souhlas.

2. Umístění přihlašování
a) Vpravo nahoře jako v DigiArchivu
b) Na stejném místě jako je nyní v AMČR

3. Patička s logy
Zadat požadavky na loga.

4. Pořadí jednotlivých sloupců
Zadat pořadí jednotlivých sloupců u jednotlivých rolí resp. oprávnění.  Vše s ohledem na sloupce, které přibudou 3D a Detektory.

**Comment by motyc** [comment]
1) varianta a + pop-up při prvním vstupu (užití cookies?)
2) varanta a
3) EU + MŠMT (https://opvvv.msmt.cz/clanek/pravidla-pro-publicitu.htm - pozor nutno dodržet pravidla v manuálech), AIS CR, ARUP, ARUB, SSC, Strategie AV21; v patičce budou i ostatní položky (copyright, kontakty, licence).
4) Jako v AMČR. Trvale neaktivní klávesy teoreticky lze posunou do druhé řady a zmenšit. Nápovědu posuneme do záhlaví a barvu využijeme pro jednu z nových nabídek.

Zde logo AMČR: 
[AMCR.ZIP](https://github.com/ARUP-CAS/aiscr-amcr/files/3476572/AMCR.ZIP)

**Comment by pbartosova** [comment]
První návrh designu amcr. Chybí některá loga.
<img width="959" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/17924714/65147003-7e564300-da1d-11e9-8887-2e9d9635719a.png">

**Comment by motyc** [comment]
Bez obsahu a menu vlevo to tolik nevyzní a celkový záměr není úplně jasný, nicméně pár poznámek:
1) Přijde mi ne úplně vhodné, jak je patička řešena na střed obrazovky a zbytek nikoli. Asi bych i obsah zápatí nechal rozběhnout do stran, nebo celý zarovnal k jedné straně.
2) Loga mi přijdou poměrně malá a není dobré, jak nejsou vertikálně na středu zápatí. Vlastní pořadí atd. bychom ještě dořešili.
3) Uděláme to tak, že zápatí bude vidět stále, nebo se bude nějak částečně či plně skrývat kvůli většímu pracovnímu prostoru? Máte zkušenosti s nějakým vhodným řešením?
4) Pruh záhlaví za logem je velice decentní a možná se až opticky ztrácí. Více bych jej vydělil ze zbytku stránky, třeba nějakým pruhem v barvě loga... zde to chce spíš názor grafika.
5) Plánujete dát centrální části nějaké pozadí, jako je tomu na úvodní stránce AMČR?

Zatím mne více nenapadá, ale je to hlavně tím, že bez obsahu je to trošku těžké hodnotit. Lépe by se to řešilo asi na sérii návrhů pro různé typy stránek.

**Comment by pbartosova** [comment]
Chtěla bych si upřesnit chování levého panelu s menu. Doteď byly položky Vyhledávání až Nápověda neviditelné pro všechny role a až když uživatel něco vybral, zobrazily se. Oproti tomu admin položky jsou viditelné už při přihlášení. Musíme se tohoto chování držet? Lepší by bylo využít nějaké obvyklé chování pro web, které by zobrazilo vždy všechny položky,co má uživatel vidět, a umožňoval by je schovat apod.
![00_webAMCR_homepage](https://user-images.githubusercontent.com/17924714/65237728-7b218c80-dadb-11e9-9d5e-91b9529cf47a.png)

**Comment by motyc** [comment]
Ano, v tomto souhlas. Není to v současnosti ideální.
