### ISSUE TITLE
Úvodní stránka pro Modul 3D

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/aiscr-amcr#61]

**Comment by pbartosova** [comment]
1. Zvolit pořadí sloupce u daných rolí.
2. Zvolit barvu pozadí pro sloupec.
3. Zvolit umístění (pořadí) pro řádek "Modul 3D" v levém panelu.
4. Dodat text pod čarou, pokud má nějaký být.

**Comment by motyc** [comment]
1. „Vložit 3D model“, „Moje 3D modely“, „Vybrat 3D model“, „Spravovat 3D modely“
2. rgb(119, 142, 152)
3. Stejné pořadí jako u kláves na hlavní obrazovce.
4. Ano, má. Zatím vložit placeholder, text zpracujeme až uvidíme něco v praxi v pohybu.
