### ISSUE TITLE
Úvodní stránka pro Modul detektory

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/aiscr-amcr#62]

**Comment by pbartosova** [comment]
1. Zvolit pořadí sloupce u daných rolí.
2. Zvolit barvu pozadí pro sloupec.
3. Zvolit umístění (pořadí) pro řádek "Modul detektory" v levém panelu.
4. Dodat text pod čarou, pokud má nějaký být.

**Comment by motyc** [comment]
1. „Zapsat nález“, „Moje nálezy“, „Vybrat nález“, „Spolupráce", „Potvrdit nálezy“, „Archivovat nálezy“
2. rgb(133, 21, 14);
3. Stejné pořadí jako u kláves na hlavní obrazovce.
4. Ano, má. Zatím vložit placeholder, text zpracujeme až uvidíme něco v praxi v pohybu.
