### ISSUE TITLE
Chybné fungování sledování změn u projektů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#65]
Ve výběrovém formuláři projektů v části "Sledovat změny projektu" se operuje se špatným datem pro stavy "zahájen v terénu" a "ukončen v terénu". Místo aby se bralo datum z pole "datum_zapisu_zahajeni", bere se "datum_zahajeni" a dtto pro ukončení. Přitom tato kritéria se vybírají pomocí data realizace jinde ve formuláři.

**Comment by pbartosova** [comment]
Nevím, jestli jsem správně pochopila, k čemu to sledování je, proto prosím raději o otestování.
Nasazena změna na serveru testu.

**Comment by motyc** [comment]
Je to správně, děkuji.
