### ISSUE TITLE
Kontrola PIAN při archivaci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#66]
Bude třeba při archivaci akce (projektové i samostatné) přidat kontrolu, zda všechny DJ mají PIAN. Nyní lze archivovat i bez splnění této podmínky, což vede k chybám v databázi a Digiarchivu.

**Comment by Najiva** [comment]
1. Pri archivaci neprojektove akce se kontroluje rada veci, krome jineho i ze kazda dokumentacni jednotka ma prave jeden pian (hlaska pri pokusu o ulozeni akce: Dokumentační jednotka: D02 (Část akce) musí mít právě jeden PIAN. ) Kontola se dela v souboru DokumentacniJednotka,java ve funkci maVPoradkuPovinne()
2. Pri archivaci projektove akce se vola uplne jiny kod a kontroluje se toho min. Asi proto tady chybi kontrola PIAN vs dokumentacni jednotka. Proto pridavam kontrolu (ze kazda DJ ma alespon jeden pian) jenom sem.

**Comment by motyc** [comment]
Děkuji za analýzu. Jediná poznámka, v bodě 2 bych slovo "alespoň" nahradil slovem "právě".

S tím mimochodem souvisí v mailu zmíněná druhá část chyby, a to ta, že v tabulce vazba_pian_parent je nutné zde zajistit unikátnost sloupce parent.

**Comment by Najiva** [comment]
Chapu to by mozna bylo fajn zajistit pridanim integritniho omezeni do databaze. Samozrejme by nastal problem co s pianama ktere maji relaci s vice DJ (v pripade ze tam jiz jsou).

**Comment by motyc** [comment]
Ano, tak jsem to myslel, vč. omezení databáze. Chyba tohoto typu je tam právě jedna (C-201806417A-D02). Odstranit lze vazbu na nepotvrzený PIAN (N-1224-189784), a smazat lze i celý tento PIAN.

**Comment by Najiva** [comment]
Ano vidim je to pro DJ s id 911403. Dobre udelam to i s omezenim.

**Comment by pbartosova** [comment]
otestováno lokálně, nasazení na test brání nedostatek místa na test prostředí. Řešíme s @MichalKminek.

**Comment by Najiva** [comment]
Nasazeno na test
