### ISSUE TITLE
Drobné opravy v databázi v souvislosti s issue #120 u Digiarchivu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#67]
Zjištění souvisí https://github.com/ARUP-CAS/arup-da-amcr/issues/120
(původně zasláno emailem)

1) PIAN P-3214-900006 nemá centroid. Není jasné proč - doplnit.
2) M-201700688A má dvakrát DJ celek akce - D02 smazat přímo z databáze (v aplikaci to nejde).
3) C-201227068A má dvakrát DJ celek akce - D02 smazat přímo z databáze
4) C-201705748A má dvakrát DJ celek akce - D01 změnit typ na část akce přímo v databázi (opět jinde nejde).

**Comment by pbartosova** [comment]
2-4 Done.
k 1. Z čeho tak usuzujete? V databázi se zdá všechno v pořádku.
select ST_X(ST_Transform(ST_Centroid(pian.geom), 4326)) as centroid_e , ST_Y(ST_Transform(ST_
Centroid(pian.geom), 4326)) as centroid_n from pian where ident_cely='P-3214-900006';
    centroid_e    |    centroid_n
------------------+------------------
 13.8693126242387 | 48.8317627264396

**Comment by motyc** [comment]
Ad 1 - Chyběl v exportu, možná tedy chyba bude jinde než v databázi.

**Comment by motyc** [comment]
V exportu PIAN stále chybí onen zmíněný centroid. Je třeba dořešit.
