### ISSUE TITLE
Úprava chování tlačítka "Zobrazit v Digiarchivu"

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#68]
Tlačítko by mělo být aktivní pouze v těch případech, kdy dokumenty v Digiarchivu indexujeme.

**Comment by pbartosova** [comment]
Nutná kontrola, co se indexuje. Je na to specifikace?
Řešení disable a enable komponent je v AMČR problematické, protože není implementováno vždy správně. Hrozí, že při tomto úkolu s odhadem 1,5MD se objeví hlubší problém, který vyžaduje další práci.

**Comment by pbartosova** [comment]
Release 5.9.10.4

**Comment by pbartosova** [comment]
Jak to tak bývá nejednalo se o úpravu na jednom místě. 
Digiarchiv neindexuje nearchivované dokumentu a dokumenty řady ZA/ZL
a) úprava dokumentů pro administrátora - tam je situace jednodušší. Tlačítko je nastaveno jako disabled pro výše uvedené dokumenty.
b) Dokumenty pod tabem Dokumentace kdekoliv v aplikaci - tam je situace složitější.
Nastavení tlačítek se různě přepisuje. Opět je nastaveno, že je tlačítko disable pro zmíněné dokumenty.
Je ale možné, že ho někde přepíše pravidlo, že tlačítko je obecně enabled pro role archivář a výše.

**Comment by motyc** [comment]
Test ok
