### ISSUE TITLE
Úpravy klienta v souvislosti s novými moduly 3D a Detektory.

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/aiscr-amcr#69]
1. Nový checkbox "Správce 3D" do Editace uživatele a Vytváření nového uživatele.
2. Nové pole "Důvěryhodnost" do formuláře Dokument, nepovinné pole textfield pro hodnoty 0-100, přidat sloupec do tabulky v databázi, upravit exporty.

**Comment by Najiva** [comment]
Checkbox pridan do klienta v commitu 53f983ca15cf2334fe1864433e485d009335c1be.
