### ISSUE TITLE
161 - Nejde vytvářet jednotky dokumentů směrem od dokumentu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#7]
Nelze vytvářet nové JD pod admin přístupem v sekci DokumentBibliografie. Platí pro produkci i test. Implementace je taková,že se nejdříve provede INSERT do tabulky jednotka_dokument s vyplněním vazby, dokumentu ale prázdným ident_cely, který se pak zapíše pomocí UPDATE tabulky. Od releasu 5.9.5 je však v databázi pro pole ident:cely nastavena podmínka not null, takže insert neprojde, a zobrazí se chybová hláška. Ke všemu po odkliknutí hlášky, proces jede dál, jako by insert prošel. Na training tento constrain nastaven není, takže tam vše "funguje".

**Comment by pbartosova** [comment]
Začínáme testovat lokálně.

**Comment by pbartosova** [comment]
Nasazeno na test.

**Comment by motyc** [comment]
Potvrzuji.
