### ISSUE TITLE
V tabulce komponent existují sirotci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#77]
Vznikají patrně tak, že v nějaké fázi došlo ke smazání DJ a záznam o DJ zůstal v tabulce atree. Komponenta tak zdánlivě má parrenta, nicméně ten již neexistuje. Týká se přinejmenším:
- C-201124287A-K01
- C-9001012A-K01
- C-9110828A-K01

Je třeba:
1) Analyzovat a opravit databázi.
2) Zjistit (pokud je to možné), kdy a jak situace mohla vzniknout.
3) Zajistit správné odstraňování položek (pokud nejde o chybu související s něčím jiným).

**Comment by motyc** [comment]
Dávám zpět repair data, protože myslím, že ještě neproběhla celková analýza, zda tam sirotků není více. Pokud se mýlím, opravte mne prosím.

**Comment by pbartosova** [comment]
Jestli dobře koukám, tak je to opět situace, kdy máme v tabulce komponenta_dokumentu pole parent a to je vždy prázdné. Vazba je ve skutečnosti uložena v atree.

**Comment by pbartosova** [comment]
Po nějaké době zkouším hledat sirotky:
select komponenta.id, komponenta.ident_cely, komponenta.parent, dokumentacni_jednotka.ident_cely as parent_ident_cely from komponenta  inner join dokumentacni_jednotka on dokumentacni_jednotka.id = komponenta.parent where dokumentacni_jednotka.ident_cely is null;
a nic nenacházím.

**Comment by motyc** [comment]
Ok, díky. Zatím zavřu, případně obnovíme.
