### ISSUE TITLE
Chyba tlačítka "Zobrazit v Digiarchivu"

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#78]
Na záložce Dokumentace u akcí (projektových i samostatných) funguje špatně tlačítko "Zobrazit v Digiarchivu". Vygeneruje vždy odkaz http://digiarchiv.amapa.cz/id/-1

V části Dokumentace a bibliografie na kartě dokumentu funguje dobře.

**Comment by pbartosova** [comment]
Opraveno lokálně, čeká na release na test.

**Comment by pbartosova** [comment]
release 5.9.8.1 test

**Comment by motyc** [comment]
Test nefunguje:
![image](https://user-images.githubusercontent.com/20186892/67240785-793c4780-f452-11e9-9f45-e267cf224846.png)

Podle mne je to špatně podepsané:
![image](https://user-images.githubusercontent.com/20186892/67241036-f5368f80-f452-11e9-8dba-86c75b445533.png)

**Comment by motyc** [comment]
Již funguje, potvrzuji.
