### ISSUE TITLE
Úpravy exportu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#79]
Rozdělení původního #14, vydělení té "snadné" části. Původní odhad cca 0,5 MD.

1) V exportu upravit pole "okres" na velká písmena, aby bylo kompatibilní s importem.

2) V exportu doplnit v polích "dalsi_katastry" přidat za každý katastr do závorky i okres, aby bylo kompatibilní s importem.

**Comment by pbartosova** [comment]
1. Upraveno pro: projekt, akce, lokalita, neident_akce, a to jak pro csv tak pro xml.

**Comment by pbartosova** [comment]
Pozn. pro mě: Bylo by dobré sjednotit, někde se bere okres z katastru a někde má svůj sloupec  v tabulce. Id se mapují na text pomocí atree. Různě se s tím kouzlí, upper/lower case, přidat ubrat okres apod. Hlavně to není jednotné.

**Comment by motyc** [comment]
Souhlas, celkové sjednocení by bylo dobré. Úprava je nicméně v pořádku.
