### ISSUE TITLE
163 - Chyby v datu zahájení akcí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#8]
1) V některých případech se špatně vyplňuje/mizí obsah pole datum_zahajeni u akcí. V datum_zahajeni_v přitom zůstává správná hodnota. Lze nalézt jako stav = 8, specifikace_data = přesně, datum_zahajeni = null

2) V AMČR se při automatickém vytvoření projektové akce zjevně správně doplní pole datum_zahajeni podle projektu, ale nikoli datum_zahajeni_v a tím pádem je položka ve formuláři zdánlivě prázdná.

3) U několika rozepsaných akcí je vyplněno pouze datum_zahajeni_v a nic jiného (např. M-201800127A), což je také podivné.

**Comment by motyc** [comment]
Doplnění k 1) Zdá se, že problém souvisí s editací archivářem/adminem. Pokud zapnu editaci akce, upravím datum a uložím, po archivaci a návratu na akci chybí datum ukončení a zobrazuje se jen datum zahájení.

**Comment by pbartosova** [comment]
Děkuji za upřesnění.

**Comment by Najiva** [comment]
Problem tady je ve funkci doSpecifikaceData v ZmenaAkce.php kde se nevim proc delaji manipulace s polem hodnot ktere se ma updatovat. Je zde je komentar  "//slozita pravidla, vice http://bugzilla.smartgis.cz/show_bug.cgi?id=4328". Je nejaka moznost dostat se k tem starym bugum?

**Comment by Najiva** [comment]
Hlavne me zajima jesli tam je pravidlo ktere rika a kdyz ano proc se ma prepsat hodnota sloupce datum_zahajeni_v do sloupce datum_zahajeni v pripade ze v sloupci specifilace_data je 2 (presne).

**Comment by motyc** [comment]
K původní bugzille se bohužel nedostaneme. Byla to interní věc SmartGIS a ani já netuším, co v ní měli evidované. Možná nejlépe pomůže podívat se přímo na to, jak logika nastavená má být, což je popsáno v následujícím dokumentu.

[logika.specifikace.data.pdf](https://github.com/ARUP-CAS/aiscr-amcr/files/3569415/logika.specifikace.data.pdf)

Koukám ale, že je to již "ready for test", už je to tedy vyřešené? Jsem teď v zahraničí a testování se budu moci věnovat až ve čtvrtek.

**Comment by Najiva** [comment]
Dekuji za info. Ano je to nakonec pripravene pro testovani. Implementace ted sedi i se specifikaci.

**Comment by motyc** [comment]
Není dořešen bod 2 z prvního komentáře (ostatní souvisí s již opraveným a opravu dat vyřešíme samostatně).

**Comment by Najiva** [comment]
Ano. Tuto situaci jsem neresil. Podivam se na to zitra.

**Comment by Najiva** [comment]
Snazim se reprodukovat chybu z bodu 2. Situace nastane kdyz kliknu na "Projkety->Zahajit vyzkum->Vyberu prihlalseny projekt->Zahajit editaci->+" V detailu docasne vytvorene akce neni nic v poli datum zahajeni pricemz by tem mel byt datum zahajeni vyzkumu ktery byl jiz zadan a je videt v detailu projektu. Je to tak?

**Comment by motyc** [comment]
Ano, jen ze zjevných důvodů nutné editovat až zahájený (P3), nikoli jen přihlášený projekt (P2). Běžný průběh je:
přihlásím projekt ke své organizaci -> zahájím výzkum -> formulář akce A se sám vygeneruje

Při použití editace ale jde o stejný proces.

**Comment by Najiva** [comment]
Rozumim. Dekuji.

**Comment by Najiva** [comment]
Pri vytvoreni nove akce pri zahajovani vyzkumu projektu ted je v poli "datum_zahajeni_v" stejne datum jako v poli "datum_zahajeni" (obe sloupce tabulka akce).

**Comment by motyc** [comment]
potvrzuji
