### ISSUE TITLE
Při archivaci se archivuje pouze akce, ale projekt zůstane ve stavu navržen k archivaci

### ISSUE THREAD

**Issue by svejci** [ARUP-CAS/aiscr-amcr#80]
Při archivování projektu C-201124607 se archivovala pouze akce, ale projekt zůstal ve stavu navržen k archivaci. Stejný výsledek byl i při pokusu o opětovnou archivaci jiný den a na jiném PC.

**Comment by pbartosova** [comment]
V logu zadna chyba neni, neni tedy jasne, proc se to stalo.
Oprava dat je to nejmensi, Uz se toto nekdy stalo?

**Comment by motyc** [comment]
Pokud víme, tak nestalo. Ondra říkal, že to zkoušel i vícekrát, ale týká se to jen tohoto projektu. Nemůže být v databázi třeba ve vazba_projekt_akce nějaký sirotek?

**Comment by motyc** [comment]
Zjistil jsem důvod. Viz #86 
Jakmile opravíte data, mělo by stačit akci znovu přearchivovat.

**Comment by motyc** [comment]
Merged #86
