### ISSUE TITLE
Oprava dat - samostatné x projektové akce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#86]
V souvislosti s předchozími převody akcí ze samostatných na projektové se u některých nezměnil typ z N na R, a proto se chybně zobrazují v obou částech. Prosím o opravu. Jde o:
C-200912548A
C-201670380A
C-201670237A
C-201441647A
C-201125320A
C-201125090A
C-201124607A
C-201123055A
C-200913002A

**Comment by motyc** [comment]
Poznámka pro mne: Až bude opraveno, přearchivovat akci C-201123055A.

**Comment by pbartosova** [comment]
Opraveno. Jen jsem nenašla vstupní sql pro původní převod, abych se pro sebe podívala, kde byla chyba.
