### ISSUE TITLE
Projekty převedené ručně do 6 / 8 mají stále dokumentaci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-amcr#87]
Je třeba spustit odpovídající script na jejich promazání. Je třeba aplikovat pouze na konkrétní projekty, protože pokud bychom to pustili na všechny projekty, předpokládám, že by se přemazaly všechny soubory s logem smazaných původních části dokumentace, což nechceme...

**Comment by pbartosova** [comment]
Držím to v paměti, ale Nedostala jsem se k tomu, abych se podívala, jak omezit projekty, na které se to spouští.
Spuštění tohoto skriptu vždy přineslo nějaké problémy.  Proto bych jeho spuštění provedla mezi svátky.

**Comment by motyc** [comment]
Ok, souhlas.

**Comment by pbartosova** [comment]
Hotovo.
